### ISSUE TITLE
End of Quarter Issue

### ISSUE THREAD

**Issue by mikedunbar20** [CodeLiftSleep/WPF-GoalLineStand-Football#41]
I ran the debugger and the game clock never resetted at 0:00. Instead, the game clock continued to run below 0:00 (for example, -1:00, -3:00). Because the clock never resetted, the game did not move to the next quarter. 

After looking at the code, I noticed this snippet.
![endofquarterissue](https://cloud.githubusercontent.com/assets/21028025/23576201/2ac15d76-0075-11e7-82b0-d62f99c126dc.JPG)

My thought is that, unless the game clock equals 0:00 EXACTLY, the game will not change over to the next quarter. My initial thought is to just add an Or statement to the above code that says if the gameTime is less than 0, initiate change of quarter/end of game sequence.

**Comment by CodeLiftSleep** [comment]
Fixed---changed to GameTime <= New TimeSpan(0,0,0) and also reset the GameTime to 15 minutes
